### ISSUE TITLE
Snappy decode vulnerable to decompression bombing

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-snappy#11]
https://github.com/status-im/nim-snappy/blob/676fa656d3a6f4e24691f3f48829c979b1b1bcdd/snappy.nim#L456

length is read from given data, then passed to `newSeq` uncritically meaning it can cause  a 4gb allocation up-front without there being supporting data behind it.

**Comment by zah** [comment]
Fixed in f449a5a47af42bcfa0d68187bb48a25475658eb0
