### ISSUE TITLE
Implement the Snappy framing format

### ISSUE THREAD

**Issue by zah** [status-im/nim-snappy#4]
The format is specified here:
https://github.com/google/snappy/blob/master/framing_format.txt

**Comment by disruptek** [comment]
Can we get some detail?  This feels like maybe an API of three functions?

**Comment by jangko** [comment]
If the input data and the commpressed result fits in memory, you can reuse the encode/decode API with additional flags.

If the input data came from a stream, we need to provide stream like interface. One for input stream and one for output stream.

I think we can design the `stream interface` as generic `pull-push` mechanism to avoid maintaining I/O buffer and only use minimal encode-decode buffer.

With this generic stream interface, we can plug in any kind of streams we like.

Both [nim-faststreams](https://github.com/status-im/nim-faststreams) and stdlib-streams can be provided as preset or example for how to use the generic stream interface.

But you are free to explore other model of interfaces or implement several of them after you have done with the core frame format.

Snappy compression are used for file stream, serializer, network and database. Considering these use cases might help in designing the interface.

Other alternative such as implement a nim-faststreams interface also have benefit it can be used in nim-serializer.

Btw, maybe @zah have his own opinion about this matter.

**Comment by zah** [comment]
Snappy is already using [nim-faststreams](https://github.com/status-im/nim-faststreams) and it's valuable to preserve this. The `OutputStream` there has some special features useful for implementing block-based compression formats such as Snappy. When you layer different streams on top of each other, there is a notion of "buffer pages" that accumulate a bit of data in memory before it's flushed to the next stream. With block-compressors or block-ciphers, you often want to buffer a precise amount of data (a single block) before you are ready to execute the encoding routine. Faststreams allows you to achieve this by controlling the minimum and maximum size of a buffer page (setting these to the same value gives you a fixed size).

Let's consider as an example that you'll have to support well. You'd want to stream Json data through a snappy compressor and then write the final result to a file. With Faststreams, you'll layer 3 writing operations on top of each other (JsonWriter writing to a SnappyStream that gets flushed to a FileStream that gets flushed to a file). The task here is to create the `FramedSnappyStream` that sits in between. Alternatively, the new functionality can exist as an option for the existing [`SnappyStream`](https://github.com/status-im/nim-snappy/blob/master/snappy.nim#L457-L470).

**Comment by zah** [comment]
Implemented in https://github.com/status-im/nim-snappy/pull/5
