### ISSUE TITLE
The fuzzing tests uncovered crashes

### ISSUE THREAD

**Issue by zah** [status-im/nim-snappy#9]
Steps to reproduce (from the nim-beacon-chain build env)

1. `cd vendor/nim-snappy`
2. `nim tests/fuzzing/run_fuzzing_test.nims framing_format`

This should quickly result in a crash.

**Comment by jangko** [comment]
@zah, the fuzzer also reveal unhandled condition in `uncompressFramedStream` of `framing.nim`.

```Nim
while input.readable(4):
```

if `readable` return false, `uncompressFramedStream` will produce incomplete output.

#10 only fix crash in `checkCrc`. How we can handle this situation?

**Comment by jangko** [comment]
Well, I think we should live with it, the spec says:

> ...It does not provide metadata checksums, so it does not protect against e.g. all forms of truncations.

**Comment by zah** [comment]
Fixed in a368549c1a473d2e580ac814f4c21342259ed9b6
